---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: feed-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: feed-service
    spec:
      initContainers:
      - name: migrate-db
        image: ghcr.io/howard12721/mikke-migrations
        env:
        - name: MIGRATION_SERVICE
          value: feed-service
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT
          value: '3306'
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: password
      containers:
      - name: feed-service
        image: ghcr.io/howard12721/mikke-feed-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50056
          name: grpc
        env:
        - name: FEED_SERVICE_PORT
          value: '50056'
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT
          value: '3306'
        - name: MARIADB_DATABASE
          value: feed_service
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: password
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: '6379'
        readinessProbe:
          grpc:
            port: 50056
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: 50056
          initialDelaySeconds: 30
          periodSeconds: 20
