apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

generators:
  - ksops-generator.yaml

images:
  - name: ghcr.io/howard12721/mikke-api
    newTag: sha-198325c2ac0e5f64fd7c6714169b0fdd64f20f0b
  - name: ghcr.io/howard12721/mikke-migrations
    newTag: sha-198325c2ac0e5f64fd7c6714169b0fdd64f20f0b
  - name: ghcr.io/howard12721/mikke-identity-service
    newTag: sha-198325c2ac0e5f64fd7c6714169b0fdd64f20f0b
  - name: ghcr.io/howard12721/mikke-friendship-service
    newTag: sha-198325c2ac0e5f64fd7c6714169b0fdd64f20f0b
  - name: ghcr.io/howard12721/mikke-post-service
    newTag: sha-198325c2ac0e5f64fd7c6714169b0fdd64f20f0b
  - name: ghcr.io/howard12721/mikke-media-service
    newTag: sha-198325c2ac0e5f64fd7c6714169b0fdd64f20f0b
  - name: ghcr.io/howard12721/mikke-guess-service
    newTag: sha-198325c2ac0e5f64fd7c6714169b0fdd64f20f0b
  - name: ghcr.io/howard12721/mikke-feed-service
    newTag: sha-198325c2ac0e5f64fd7c6714169b0fdd64f20f0b
  - name: ghcr.io/howard12721/mikke-notification-service
    newTag: sha-198325c2ac0e5f64fd7c6714169b0fdd64f20f0b

replicas:
  - name: api
    count: 3
  - name: identity-service
    count: 2
  - name: friendship-service
    count: 2
  - name: post-service
    count: 2
  - name: media-service
    count: 2
  - name: guess-service
    count: 2
  - name: feed-service
    count: 2
  - name: notification-service
    count: 2
