apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

generators:
  - ksops-generator.yaml

images:
  - name: ghcr.io/howard12721/mikke-api
    newTag: sha-b12a4a029abef5a409b48bbfc3e79dcf799bc991
  - name: ghcr.io/howard12721/mikke-migrations
    newTag: sha-b12a4a029abef5a409b48bbfc3e79dcf799bc991
  - name: ghcr.io/howard12721/mikke-identity-service
    newTag: sha-b12a4a029abef5a409b48bbfc3e79dcf799bc991
  - name: ghcr.io/howard12721/mikke-friendship-service
    newTag: sha-b12a4a029abef5a409b48bbfc3e79dcf799bc991
  - name: ghcr.io/howard12721/mikke-post-service
    newTag: sha-b12a4a029abef5a409b48bbfc3e79dcf799bc991
  - name: ghcr.io/howard12721/mikke-media-service
    newTag: sha-b12a4a029abef5a409b48bbfc3e79dcf799bc991
  - name: ghcr.io/howard12721/mikke-guess-service
    newTag: sha-b12a4a029abef5a409b48bbfc3e79dcf799bc991
  - name: ghcr.io/howard12721/mikke-feed-service
    newTag: sha-b12a4a029abef5a409b48bbfc3e79dcf799bc991
  - name: ghcr.io/howard12721/mikke-notification-service
    newTag: sha-b12a4a029abef5a409b48bbfc3e79dcf799bc991

replicas:
  - name: api
    count: 3
  - name: identity-service
    count: 2
  - name: friendship-service
    count: 2
  - name: post-service
    count: 2
  - name: media-service
    count: 2
  - name: guess-service
    count: 2
  - name: feed-service
    count: 2
  - name: notification-service
    count: 2
