apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

generators:
  - ksops-generator.yaml

images:
  - name: ghcr.io/howard12721/mikke-api
    newTag: sha-d6b4bd98b1aa049ccd9cb1a41de072cee0cf5bd4
  - name: ghcr.io/howard12721/mikke-migrations
    newTag: sha-d6b4bd98b1aa049ccd9cb1a41de072cee0cf5bd4
  - name: ghcr.io/howard12721/mikke-identity-service
    newTag: sha-d6b4bd98b1aa049ccd9cb1a41de072cee0cf5bd4
  - name: ghcr.io/howard12721/mikke-friendship-service
    newTag: sha-d6b4bd98b1aa049ccd9cb1a41de072cee0cf5bd4
  - name: ghcr.io/howard12721/mikke-post-service
    newTag: sha-d6b4bd98b1aa049ccd9cb1a41de072cee0cf5bd4
  - name: ghcr.io/howard12721/mikke-media-service
    newTag: sha-d6b4bd98b1aa049ccd9cb1a41de072cee0cf5bd4
  - name: ghcr.io/howard12721/mikke-guess-service
    newTag: sha-d6b4bd98b1aa049ccd9cb1a41de072cee0cf5bd4
  - name: ghcr.io/howard12721/mikke-feed-service
    newTag: sha-d6b4bd98b1aa049ccd9cb1a41de072cee0cf5bd4
  - name: ghcr.io/howard12721/mikke-notification-service
    newTag: sha-d6b4bd98b1aa049ccd9cb1a41de072cee0cf5bd4

replicas:
  - name: api
    count: 3
  - name: identity-service
    count: 2
  - name: friendship-service
    count: 2
  - name: post-service
    count: 2
  - name: media-service
    count: 2
  - name: guess-service
    count: 2
  - name: feed-service
    count: 2
  - name: notification-service
    count: 2
