apiVersion: v1
kind: Secret
metadata:
    name: mariadb-auth
    namespace: mikke
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:S69aR1ayJEgWN1dVxK4cPTX83khtDsaOq5A=,iv:I2n1IJPcQxHguUnbMZwQUtvLRWvxesvPEfNYBO7RcrI=,tag:oRYIjqyZTToaL/U8jkkJOQ==,type:str]
    username: ENC[AES256_GCM,data:ZXuwapw=,iv:7HznIPbEpdEIgiGnu8Ds6g++9YhnnguOR3qJsN3e7bA=,tag:Y9A6paP8KO41rC4LZBJzcw==,type:str]
    password: ENC[AES256_GCM,data:GIQBtCY3dZHiuxww8/Udt6NaKqjBmodutb8=,iv:8LLwm64AFKuctK1+jnNlxQxd/CW/MFt9r8wUI8ICyzM=,tag:HSXFs4tzoRq3yFwtMu7LXw==,type:str]
sops:
    age:
        - recipient: age16w7nxe8es9gnkgsmyl70aejcua650kqr6883u5qms9vjl3ytxvnsu3y0ty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV1o4cm9lUVJFREdCb09L
            QVgyd1hOdDNkR1hJOWI3bjFJUjQ5SjBKSUZnClhsbFgvREFiMU5yVUhYb0lVNzBJ
            Ynk0bUVwcGdaUktkNzZRUGpkRHVWTG8KLS0tIGRNa1lpVzRHR0Yyc1ZDRWt2dmxy
            M2lkVjhpTVNhbG9OQ3JBTXVpRk42ZTAK5faryiuQXn8RcxpSxLoMB2aN7booimbZ
            TKOuSZRtPVC2AKjnTQkzRLq6Fu1AbROwFPVE3HB4fqPUuQzrwVu6hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T08:46:13Z"
    mac: ENC[AES256_GCM,data:msEENsAhpbsUHVavT3CsSmqNtivaNZEtfQ5a8j3q2cG1CiPBdH1/lcjuBN411LT+JUQNp6r35m5QqNKN6sPNxOWMjzJATAZey4q5tCUUm8/xq5gw0utflCRiDu+R2QJBZw9ZvMi9ZzWz+bqufWAM/1c/wL5UbCvM7FumhbfB7Jk=,iv:xwjG2k0SpztF5MEX14DETBWgH1E26iB9L6aDpW4A0r4=,tag:WDRv/StExT7F4pPYZ0d4Cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: identity-auth
    namespace: mikke
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:Ub13odsLbzErDqapRHzwBaFzj5MHO97H,iv:LWBUnN9Get4n9PHMK1RZMbmy8oJme+R+QfPW651939k=,tag:Ci0YAXg8B5nviS3ehxnggw==,type:str]
sops:
    age:
        - recipient: age16w7nxe8es9gnkgsmyl70aejcua650kqr6883u5qms9vjl3ytxvnsu3y0ty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV1o4cm9lUVJFREdCb09L
            QVgyd1hOdDNkR1hJOWI3bjFJUjQ5SjBKSUZnClhsbFgvREFiMU5yVUhYb0lVNzBJ
            Ynk0bUVwcGdaUktkNzZRUGpkRHVWTG8KLS0tIGRNa1lpVzRHR0Yyc1ZDRWt2dmxy
            M2lkVjhpTVNhbG9OQ3JBTXVpRk42ZTAK5faryiuQXn8RcxpSxLoMB2aN7booimbZ
            TKOuSZRtPVC2AKjnTQkzRLq6Fu1AbROwFPVE3HB4fqPUuQzrwVu6hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T08:46:13Z"
    mac: ENC[AES256_GCM,data:msEENsAhpbsUHVavT3CsSmqNtivaNZEtfQ5a8j3q2cG1CiPBdH1/lcjuBN411LT+JUQNp6r35m5QqNKN6sPNxOWMjzJATAZey4q5tCUUm8/xq5gw0utflCRiDu+R2QJBZw9ZvMi9ZzWz+bqufWAM/1c/wL5UbCvM7FumhbfB7Jk=,iv:xwjG2k0SpztF5MEX14DETBWgH1E26iB9L6aDpW4A0r4=,tag:WDRv/StExT7F4pPYZ0d4Cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: garage-auth
    namespace: mikke
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
    rpc-secret: ENC[AES256_GCM,data:5mdco52omUVEHCGtXebLQtTPpSc3HYzZyAdUPGKwgr5cKComDRzJ6kUiWqEkwzyUcYeSdgBDOBf0cRxDTs1xtA==,iv:Eqd7a5zDsj2IX7NisatQhhS1E7Xi3pFQ6alGI4Fzgw8=,tag:ZaD1DKdtkr+UUe9l/zh63w==,type:str]
    admin-token: ENC[AES256_GCM,data:nr0EPxsuX4VhG9/aEWTRXzObDjnhR1P48cmRUHnS92uif4WNRvp1f9K3AVE=,iv:ApvcReqJlJjfpLVFAAvcck4C+DC8KyhngkB6IyBX3Sc=,tag:CuBHeMEoGEObgJ6td2nhkA==,type:str]
    metrics-token: ENC[AES256_GCM,data:E3oKMH7OgbKYqQM9Y02n8BYjVPWdM42C62vEv9FS/cf9mfLRpKBLfzq3bYY=,iv:Ro26vhfErA5vxzq7yx+fXZdksPR82a7WfIosNH+8DRs=,tag:w1CeQ7FdnnzURpTtAqnFWw==,type:str]
    access-key-id: ENC[AES256_GCM,data:WyQkSo3ySgrW3x76/JYf2s82fbx0VhqtLs5r/3E92ZM+vA==,iv:B9z3TnEZ6suFmm0duL5TnpE/A7xZla+sr+5cKXLMrNo=,tag:GFKyIRr4Fh6EUUJvGQDSdQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:bGOdWbDUavpNz1jBS6OIWNhMFzcAbldd+c5ZhucmEmpUuU9ElePvsSR4m1XLoNhY8bQlTsY5nbSPprzIfzgTAg==,iv:7B828ZnVVHB5fbzlWPaTTeUjO9KtqNYb4lajq1Sc5Ok=,tag:5rTOFsGYa5yXfNSP4Mmjhg==,type:str]
sops:
    age:
        - recipient: age16w7nxe8es9gnkgsmyl70aejcua650kqr6883u5qms9vjl3ytxvnsu3y0ty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV1o4cm9lUVJFREdCb09L
            QVgyd1hOdDNkR1hJOWI3bjFJUjQ5SjBKSUZnClhsbFgvREFiMU5yVUhYb0lVNzBJ
            Ynk0bUVwcGdaUktkNzZRUGpkRHVWTG8KLS0tIGRNa1lpVzRHR0Yyc1ZDRWt2dmxy
            M2lkVjhpTVNhbG9OQ3JBTXVpRk42ZTAK5faryiuQXn8RcxpSxLoMB2aN7booimbZ
            TKOuSZRtPVC2AKjnTQkzRLq6Fu1AbROwFPVE3HB4fqPUuQzrwVu6hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T08:46:13Z"
    mac: ENC[AES256_GCM,data:msEENsAhpbsUHVavT3CsSmqNtivaNZEtfQ5a8j3q2cG1CiPBdH1/lcjuBN411LT+JUQNp6r35m5QqNKN6sPNxOWMjzJATAZey4q5tCUUm8/xq5gw0utflCRiDu+R2QJBZw9ZvMi9ZzWz+bqufWAM/1c/wL5UbCvM7FumhbfB7Jk=,iv:xwjG2k0SpztF5MEX14DETBWgH1E26iB9L6aDpW4A0r4=,tag:WDRv/StExT7F4pPYZ0d4Cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
