apiVersion: v1
kind: Secret
metadata:
    name: mariadb-auth
    namespace: mikke
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:kLVZmlrCRnkXOlkPg1jpAo29gex2x51E6Qc=,iv:NofgPjh1GTCGmIuByR6TKDL0tPV/FBYmRU9Uav1ARDw=,tag:tfgps7Ht/WhwMzcziL5tbQ==,type:str]
    username: ENC[AES256_GCM,data:HxF+3BY=,iv:Mr9aoS8oH4JOSPMtrx/tNHsJ28nLDdTDmMs1M0e7m9I=,tag:PlLRHoj00SrIVSUbrPFyJQ==,type:str]
    password: ENC[AES256_GCM,data:rrD4iyxye46yCwC6Ot7Vi27cfKa+LvTGON8=,iv:aTygAB78MflSfp+F+KyHlgcYlMKns+FmYg41aFsoPLI=,tag:beU3EwASqYJ718DPMLMd0g==,type:str]
sops:
    age:
        - recipient: age16w7nxe8es9gnkgsmyl70aejcua650kqr6883u5qms9vjl3ytxvnsu3y0ty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVDZlVHdtWXhSWjNzUkhP
            UE9tZTRaSUk0V0RNOUZmWjl2WHVLYjdackYwCmw0cnNIL0lPMnpsWlNoMzF2WjBC
            T3c5S2NkNURHSGlvR2dyazQ2T3Eya1EKLS0tIDhYb0FDclk3LzBhY3IzZnU5NHND
            TDZpV3RnaW00MWFvR0k5eFg5UWp4VVEK3Zh8nbv1WJK+T1CnvY0nvm+4dw9RsNyV
            Hrj9GWEfwQeWCF+AX18vxwfHUAgn81tqJ6D5z+xnomWjaLiQExl6CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T13:06:47Z"
    mac: ENC[AES256_GCM,data:Q2quITdZg99YmfvCovfTW/71byPoJ4wuR8YukLQaUp3TcN2dIyJOXq2Qatz7cfCbEXaJP6XViJm7Zf/VLJo/p7XoNhTSzWDRBWn95j7QMwd7rDmAakVDVKJLl12mF7ZGxqKhIKcYBEe6laDBbvXnTn+STbPfQuZSpy31XzRyvvU=,iv:qgHCi3nqTHfESq87KveCAi/JtXl4DrEEQAUFFBLOocg=,tag:qyk30d06P8hGt7RjLC9rtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: identity-auth
    namespace: mikke
    annotations:
        argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:0489HxrYz3imkNe99EUuEVWd3bs+FEEe,iv:mTlXdTgg3P11/sbCBCC7B1GLXnLp5y9Ye4iuuIkI54k=,tag:DHTMVo9d1HPT8Zt8yqHaAQ==,type:str]
sops:
    age:
        - recipient: age16w7nxe8es9gnkgsmyl70aejcua650kqr6883u5qms9vjl3ytxvnsu3y0ty
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVDZlVHdtWXhSWjNzUkhP
            UE9tZTRaSUk0V0RNOUZmWjl2WHVLYjdackYwCmw0cnNIL0lPMnpsWlNoMzF2WjBC
            T3c5S2NkNURHSGlvR2dyazQ2T3Eya1EKLS0tIDhYb0FDclk3LzBhY3IzZnU5NHND
            TDZpV3RnaW00MWFvR0k5eFg5UWp4VVEK3Zh8nbv1WJK+T1CnvY0nvm+4dw9RsNyV
            Hrj9GWEfwQeWCF+AX18vxwfHUAgn81tqJ6D5z+xnomWjaLiQExl6CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T13:06:47Z"
    mac: ENC[AES256_GCM,data:Q2quITdZg99YmfvCovfTW/71byPoJ4wuR8YukLQaUp3TcN2dIyJOXq2Qatz7cfCbEXaJP6XViJm7Zf/VLJo/p7XoNhTSzWDRBWn95j7QMwd7rDmAakVDVKJLl12mF7ZGxqKhIKcYBEe6laDBbvXnTn+STbPfQuZSpy31XzRyvvU=,iv:qgHCi3nqTHfESq87KveCAi/JtXl4DrEEQAUFFBLOocg=,tag:qyk30d06P8hGt7RjLC9rtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
