---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: identity-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: identity-service
    spec:
      initContainers:
      - name: migrate-db
        image: ghcr.io/howard12721/mikke-migrations
        env:
        - name: MIGRATION_SERVICE
          value: identity-service
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT
          value: '3306'
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: password
      containers:
      - name: identity-service
        image: ghcr.io/howard12721/mikke-identity-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
          name: grpc
        env:
        - name: IDENTITY_SERVICE_PORT
          value: '50051'
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT
          value: '3306'
        - name: MARIADB_DATABASE
          value: identity_service
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: password
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: '6379'
        - name: IDENTITY_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: identity-auth
              key: jwt-secret
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 30
          periodSeconds: 20
