---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: media-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: media-service
    spec:
      initContainers:
      - name: migrate-db
        image: ghcr.io/howard12721/mikke-migrations
        env:
        - name: MIGRATION_SERVICE
          value: media-service
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT
          value: '3306'
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: password
      containers:
      - name: media-service
        image: ghcr.io/howard12721/mikke-media-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50054
          name: grpc
        env:
        - name: MEDIA_SERVICE_PORT
          value: '50054'
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT
          value: '3306'
        - name: MARIADB_DATABASE
          value: media_service
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: password
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: '6379'
        - name: OBJECT_STORAGE_ENDPOINT
          value: http://garage:3900
        - name: OBJECT_STORAGE_REGION
          value: garage
        - name: OBJECT_STORAGE_BUCKET
          value: mikke-media
        - name: OBJECT_STORAGE_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: garage-auth
              key: access-key-id
        - name: OBJECT_STORAGE_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: garage-auth
              key: secret-access-key
        - name: OBJECT_STORAGE_FORCE_PATH_STYLE
          value: 'true'
        readinessProbe:
          grpc:
            port: 50054
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: 50054
          initialDelaySeconds: 30
          periodSeconds: 20
