---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guess-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guess-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guess-service
    spec:
      initContainers:
      - name: wait-for-mariadb
        image: busybox:1.36
        command:
        - sh
        - "-c"
        - until nc -z mariadb 3306; do sleep 2; done
      - name: wait-for-redis
        image: busybox:1.36
        command:
        - sh
        - "-c"
        - until nc -z redis 6379; do sleep 2; done
      - name: migrate-db
        image: ghcr.io/howard12721/mikke-migrations:latest
        env:
        - name: MIGRATION_SERVICE
          value: guess-service
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT
          value: '3306'
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: password
      containers:
      - name: guess-service
        image: ghcr.io/howard12721/mikke-guess-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50055
          name: grpc
        env:
        - name: GUESS_SERVICE_PORT
          value: '50055'
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT
          value: '3306'
        - name: MARIADB_DATABASE
          value: guess_service
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-auth
              key: password
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: '6379'
        readinessProbe:
          grpc:
            port: 50055
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: 50055
          initialDelaySeconds: 30
          periodSeconds: 20
