CREATE DATABASE IF NOT EXISTS identity_service;
CREATE DATABASE IF NOT EXISTS friendship_service;
CREATE DATABASE IF NOT EXISTS post_service;
CREATE DATABASE IF NOT EXISTS media_service;
CREATE DATABASE IF NOT EXISTS guess_service;
CREATE DATABASE IF NOT EXISTS feed_service;
CREATE DATABASE IF NOT EXISTS notification_service;

