---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app.kubernetes.io/name: notification-service
  ports:
  - name: grpc
    port: 50057
    targetPort: grpc
