apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mikke

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

configMapGenerator:
  - name: mariadb-initdb
    files:
      - 01-create-databases.sql=sql/01-create-databases.sql

resources:
  - namespace.yaml
  - infrastructure.yaml
  - services
