---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
      - name: api
        image: ghcr.io/howard12721/mikke-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: '8080'
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: '6379'
        - name: MARIADB_HOST
          value: mariadb
        - name: MARIADB_PORT
          value: '3306'
        - name: IDENTITY_SERVICE_HOST
          value: identity-service
        - name: IDENTITY_SERVICE_PORT
          value: '50051'
        - name: IDENTITY_SERVICE_TARGET
          value: dns:///identity-service:50051
        - name: FRIENDSHIP_SERVICE_HOST
          value: friendship-service
        - name: FRIENDSHIP_SERVICE_PORT
          value: '50052'
        - name: FRIENDSHIP_SERVICE_TARGET
          value: dns:///friendship-service:50052
        - name: POST_SERVICE_HOST
          value: post-service
        - name: POST_SERVICE_PORT
          value: '50053'
        - name: POST_SERVICE_TARGET
          value: dns:///post-service:50053
        - name: MEDIA_SERVICE_HOST
          value: media-service
        - name: MEDIA_SERVICE_PORT
          value: '50054'
        - name: MEDIA_SERVICE_TARGET
          value: dns:///media-service:50054
        - name: GUESS_SERVICE_HOST
          value: guess-service
        - name: GUESS_SERVICE_PORT
          value: '50055'
        - name: GUESS_SERVICE_TARGET
          value: dns:///guess-service:50055
        - name: NOTIFICATION_SERVICE_HOST
          value: notification-service
        - name: NOTIFICATION_SERVICE_PORT
          value: '50057'
        - name: NOTIFICATION_SERVICE_TARGET
          value: dns:///notification-service:50057
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 20
